# Generated by Django 5.2.5 on 2025-08-13 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Anime')),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Personaje')),
                ('biografia', models.TextField(verbose_name='Biografía')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='characters/', verbose_name='Imagen')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personajes', to='mi_app.anime')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
